version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'weekly'
    groups:
      dependencies:
        patterns:
          - '*'
    open-pull-requests-limit: 10

  # Backend dependencies
  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'weekly'
    groups:
      dependencies:
        patterns:
          - '*'
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'
    open-pull-requests-limit: 10
