name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - server/**
      - .github/workflows/backend.yml
  pull_request:
    branches: [main]
    paths:
      - server/**
      - .github/workflows/backend.yml

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
          cache-dependency-path: ./server/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn tsc --noEmit

      - name: Lint and Format
        uses: trunk-io/trunk-action@v1
        with:
          arguments: --filter=eslint,prettier ./server

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
