name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - 'server/**'
      - '**/Dockerfile'
      - '**/docker-compose.yml'
      - '.dockerignore'
  pull_request:
    branches: ["main"]
    paths:
      - 'server/**'
      - '**/Dockerfile'
      - '**/docker-compose.yml'
      - '.dockerignore'
  workflow_dispatch:  

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: davidoduneye/productivity:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull davidoduneye/productivity:latest
            docker-compose down
            docker-compose up -d
