name: Annotate PR with trunk issues

on:
  workflow_run:
    workflows: ['Backend CI', 'Frontend CI', 'Weekly Full Trunk Check']
    types: [completed]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  trunk_check:
    name: Trunk Code Quality Annotate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
